/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-05-11 12:47:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Mentorship Platform | Home</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/home.css\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .hero .icon {\r\n");
      out.write("            font-size: 60px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .hero h1 {\r\n");
      out.write("            font-size: 42px;\r\n");
      out.write("        }\r\n");
      out.write("        .hero p {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            transition: transform 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Hero Section -->\r\n");
      out.write("    <header class=\"hero\">\r\n");
      out.write("        <div class=\"icon\">\r\n");
      out.write("            <i class=\"fas fa-brain\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h1>Welcome to Mentorship Platform</h1>\r\n");
      out.write("        <p>Connect. Learn. Grow.</p>\r\n");
      out.write("        <div class=\"hero-buttons\">\r\n");
      out.write("            <a href=\"register.jsp\" class=\"btn\">Register</a>\r\n");
      out.write("            <a href=\"login.jsp\" class=\"btn\">Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- About Section -->\r\n");
      out.write("    <section class=\"about\">\r\n");
      out.write("        <h2>Why Join Us?</h2>\r\n");
      out.write("        <p>We provide a dynamic platform where mentors share knowledge and mentees seek guidance. Whether you're seeking career advice or looking to help others, we connect you with the right people.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Features Section -->\r\n");
      out.write("    <section class=\"features\">\r\n");
      out.write("        <div class=\"feature-card\">\r\n");
      out.write("            <i class=\"fas fa-user-graduate fa-2x\"></i>\r\n");
      out.write("            <h3>For Mentees</h3>\r\n");
      out.write("            <p>Find experienced mentors to guide your academic or professional journey.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"feature-card\">\r\n");
      out.write("            <i class=\"fas fa-chalkboard-teacher fa-2x\"></i>\r\n");
      out.write("            <h3>For Mentors</h3>\r\n");
      out.write("            <p>Share your expertise and give back by mentoring the next generation.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"feature-card\">\r\n");
      out.write("            <i class=\"fas fa-comments fa-2x\"></i>\r\n");
      out.write("            <h3>Conversations</h3>\r\n");
      out.write("            <p>Seamless communication through appointment booking and feedback channels.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Testimonials Section -->\r\n");
      out.write("    <section class=\"testimonials\">\r\n");
      out.write("        <h2>User Testimonials</h2>\r\n");
      out.write("        <div class=\"testimonial\">\r\n");
      out.write("            <p>\"This platform helped me connect with a mentor who guided me through my final year project!\"</p>\r\n");
      out.write("            <span>- Priya, BTech Student</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"testimonial\">\r\n");
      out.write("            <p>\"It’s fulfilling to share my industry experience with students. Highly recommend!\"</p>\r\n");
      out.write("            <span>- Rajeev, Software Engineer</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>© 2025 Mentorship Platform | Designed by QuadSynk</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
