/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-05-11 16:41:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login - Mentorship Platform</title>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("/* Global styles */\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Arial', sans-serif;\r\n");
      out.write("    background: linear-gradient(135deg, #4CAF50, #81C784);\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Container for login form */\r\n");
      out.write(".login-container {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.15);\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 420px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-container:hover {\r\n");
      out.write("    transform: scale(1.02);\r\n");
      out.write("    box-shadow: 0 12px 24px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Heading */\r\n");
      out.write("h2 {\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Form elements */\r\n");
      out.write("form {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    gap: 15px; /* Reduced gap */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    margin-bottom: 6px; /* Reduced margin */\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"email\"],\r\n");
      out.write("input[type=\"password\"] {\r\n");
      out.write("    padding: 12px 40px 12px 14px; /* Reduced padding */\r\n");
      out.write("    margin-bottom: 15px; /* Reduced bottom margin */\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"email\"]:focus,\r\n");
      out.write("input[type=\"password\"]:focus {\r\n");
      out.write("    border-color: #4CAF50;\r\n");
      out.write("    box-shadow: 0 0 5px rgba(76, 175, 80, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"email\"]::placeholder,\r\n");
      out.write("input[type=\"password\"]::placeholder {\r\n");
      out.write("    color: #bbb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"email\"]:before,\r\n");
      out.write("input[type=\"password\"]:before {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 15px;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    color: #aaa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"email\"]:before {\r\n");
      out.write("    content: url('https://img.icons8.com/ios-filled/50/000000/email.png');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"password\"]:before {\r\n");
      out.write("    content: url('https://img.icons8.com/ios-filled/50/000000/lock.png');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Submit Button */\r\n");
      out.write("input[type=\"submit\"] {\r\n");
      out.write("    padding: 12px;\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"]:hover {\r\n");
      out.write("    background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive Design */\r\n");
      out.write("@media (max-width: 480px) {\r\n");
      out.write("    .login-container {\r\n");
      out.write("        padding: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        font-size: 22px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"email\"],\r\n");
      out.write("    input[type=\"password\"],\r\n");
      out.write("    input[type=\"submit\"] {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("/* Back to Home Button */\r\n");
      out.write(".back-btn {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 12px;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-btn:hover {\r\n");
      out.write("    background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"login-container\">\r\n");
      out.write("        <h2>Login</h2>\r\n");
      out.write("        <form action=\"login\" method=\"post\">\r\n");
      out.write("            <label for=\"email\">Email:</label><br>\r\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"password\">Password:</label><br>\r\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"submit\" value=\"Login\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"back-btn\">Back to Home</a>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
